# Generated by Django 3.0.10 on 2021-05-30 17:48

import api.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_photo_prediction_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_on', models.DateTimeField(db_index=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
                ('favorited', models.BooleanField(db_index=True, default=False)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('owner', models.ForeignKey(default=None, on_delete=models.SET(api.models.user.get_deleted_user), to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(to='api.Photo')),
                ('shared_to', models.ManyToManyField(related_name='album_case_shared_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('timestamp', 'owner')},
            },
        ),
    ]
