# Generated by Django 3.0.10 on 2021-05-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_albumcase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumCase',
        ),
    ]
