# Generated by Django 3.1.8 on 2021-07-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_albumcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumcase',
            name='date',
        ),
        migrations.RemoveField(
            model_name='albumcase',
            name='location',
        ),
        migrations.AddField(
            model_name='albumcase',
            name='created_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='albumcase',
            name='description',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AddField(
            model_name='albumcase',
            name='public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='albumcase',
            name='title',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
