# Generated by Django 3.1.8 on 2021-07-20 14:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210720_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumuser',
            name='geolocation_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, null=True),
        ),
    ]
