# Generated by Django 3.1.8 on 2021-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_albumuser_geolocation_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumuser',
            name='geolocation_json',
        ),
        migrations.AddField(
            model_name='albumuser',
            name='search_location',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
